language: bash

sudo: true

env:
  - VERSION=centos7

services:
  - docker

before_script:
  - env | sort
  - export image="nuocw/testing-environment:$VERSION"

script:
  - test "$(head -n1 Dockerfile)" = "FROM nuocw/buildpack-deps:$VERSION"
